import React, { FunctionComponent } from "react";
import Ondefy from "/startups/OnDefy.webp";
import Spectra from "/startups/spectra_logo.png";
import Crypties from "/startups/Crypties_white.webp";
import Honey from "/startups/HONEY.webp";
import AscentAdAstra from "/startups/AAA Logotext White.webp";
import Image, { StaticImageData } from "next/image";

const Startups = () => {
  return (
    <div className="bg-dark-100 flex flex-col py-36 font-semibold w-full gap-16 justify-center items-center p-10">
      <div className="w-5/6 flex flex-col gap-16">
        <div className="flex flex-row">
          <div className="flex flex-col items-center md:items-start justify-start gap-4 w-full">
            <div className="flex flex-col items-center md:items-start md:gap-4 md:flex-row">
              <span className="bg-gradient-to-r bg-clip-text text-transparent from-dark-200 to-orange-500 text-4xl">
                STARTUPS
              </span>
              <span className="bg-gradient-to-r bg-clip-text text-transparent from-gray-100 to-gray-500 text-4xl">
                ACCELERATOR
              </span>
            </div>
            <span className="text-gray-400 md:text-left text-center">
              The BSA is also a wonderful startups incubator. We incentivize
              students and collaborators to build as much value as they can.
            </span>
          </div>
          {/*<div className="w-4/12 h-full flex items-center justify-center">
                        <img src={Rocket} className="h-44"/>
                    </div>*/}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-12">
          <Startup
            img={AscentAdAstra}
            title="Digital agency for Web3 design and development:"
            description="Get a website or DeFi webApp which suits your needs and goals, using top tier UI/UX and smart contracts integration."
            link_view="https://ascentadastra.com"
          />
          <Startup
            img={Spectra}
            title="The derivatives layer for DeFi yield :"
            description="Speculate on the evolution of the yield generated by different DeFi protocols. Hedge your risk on your passive revenue."
            link_view="https://www.spectra.finance/"
          />
          <Startup
            img={Ondefy}
            title="Get the best out of DeFi
                    in one place :"
            description="Swap any token from any chain, generate yield, leverage your assets and simply access the best protocols."
            link_view="https://ondefy.com"
          />
          <Startup
            img={Honey}
            title="Turn NFTs into financial assets :"
            description="Honey Labs pioneers liquidity solutions for NFTs, and allows you to access DeFi through your NFTs."
            link_view="https://y.at/%F0%9F%8D%AF%F0%9F%8D%AF%F0%9F%90%9D"
          />
          <Startup
            img={Crypties}
            title="Acquire
                    cryptocurrencies
                    anywhere with ease :"
            description="With Crypties you can acquire crypto easily nearly anywhere with
                    more than 800 points of sales in Switzerland."
            link_view="https://crypties.ch/en"
          />
        </div>
      </div>
    </div>
  );
};

export default Startups;

//CReation of "Project"
const Startup: FunctionComponent<{
  img?: StaticImageData;
  title?: string;
  description?: string;
  link_view?: string;
}> = ({ img, title, description, link_view }) => {
  return (
    <div
      className=" relative flex flex-col w-full transition-all duration-100 transform rounded-lg overflow-hidden bg-opacity-10 group hover:bg-opacity-75"
      style={{ willChange: "transform" }}
    >
      <div className="relative flex flex-col items-center w-full pt-12 pb-20 overflow-visible transition-all duration-100 bg-[#021741]  ">
        <div className="w-9/12 h-80 flex flex-col gap-8">
          <div className="flex items-center justify-center h-1/5 mb-2">
            {img ? (
              <Image alt="startup logo" src={img} />
            ) : (
              <div className="z-20 flex flex-row items-center justify-center w-12 h-12 text-3xl text-primary-200">
                ?
              </div>
            )}
          </div>
          <div className="w-full text-left">
            <span className="text-white sm:text-base text-sm font-semibold pointer-events-none">
              {title}
            </span>
          </div>
          <div className=" w-full text-left">
            <span className="text-white sm:text-base text-sm italic font-normal pointer-events-none">
              {description}
            </span>
          </div>

          <div className="w-full flex items-center justify-center ">
            <a
              href={link_view}
              target="_blank"
              rel="noopener noreferrer"
              className="absolute bottom-10 flex mt-10 w-3/6 items-center justify-center border border-dark-400 text-gray-200 font-normal text-base text-opacity-50 p-2 rounded-md
                            hover:text:gray-100 hover:bg-opacity-20 hover:bg-dark-400 hover:text-opacity-100 duration-100"
            >
              DISCOVER
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};
